### PR TITLE
[feature #163462068] Consume delete meetup endpoint

### PR DESCRIPTION
**Pull request by abidex4yemi**
### What does this PR do?

  Connect /meetup endpoint with front-end admin dashboard

### Description of the task to be completed?

  * Have the following listed task completed:

    `Check if logged in user is an admin`

    `Validate user input`

    `delete a specific meetup record if exist`

    `show feedback message on error or success`

    `reload admin dashboard and show all meetup record`

 ### How should this be tested manually?

   * By visiting the link listed below

     [Meetup-questioner-app](https://abidex4yemi.github.io/meet-up-questioner/admin-dashboard.html)

### What are the relevant pivotal tracker stories?

163462068, 163729093

admin_dashboard

### CODE REVIEW

**Review by JCanaks — CHANGES_REQUESTED** [review]
@abidex4yemi Ok nice work here. Just one minor feedback. Once this is implemented you can go ahead and merge this. 
Centralise the `Are you sure you want to delete meetup?` question within the modal and also the spaces between the buttons is too far apart let the button come close together with just moderate spacing and position them underneath the centralize question. Once this is done send me the link to the updated App on heroku
screen shot 2019-02-05 at 4 25 37 pm

**Comment by JCanaks** [comment]
@abidex4yemi Also next time pls provide screenshots as part of your PR description.

**Comment by JCanaks** [comment]
@abidex4yemi The PT story IDs specified in you PR should link me to your stories on PT use ` < a href='link to story'> Story id </a>` to implement that.

**Comment by JCanaks** [comment]
Also pls use the format specifed in --> https://github.com/andela/workdey/wiki/Commit-Message-Convention#format-of-the-commit-message for commit messages moving forward. An example of a commit message is shown below
screen shot 2019-02-05 at 4 50 59 pm

**Comment by JCanaks** [comment]
@abidex4yemi I should also see coverage details as part of the checks

**Comment by abidex4yemi** [comment]
> @abidex4yemi Also next time pls provide screenshots as part of your PR description.

Noted

**Pull request merged**
